<a href="https://colab.research.google.com/github/srikanthkakumanu/do-hugging-face/blob/master/transformers_hf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# Transformers using GPT from Hugging Face Framework

## Loading the Model

There are two ways to load the models using **transformers library**.

Using AutoTokenizer + AutoModel &mdash; Gives fine-grained control over tokenization and model setup.   
Load the model via Pipeline

*   Using **AutoTokenizer + AutoModel**:
    *     Gives fined-grained control over **tokenization** and **model setup**.
    *     Full control over **tokenization, model execution** and **post-processing**. we must handle tokenization, inference, and decoding manually. Requires understanding of model input/output formats.
    *     Works for model **training**, **fine-tuning** and **inference**.

*   Using **Pipeline**:
    *     This high-level, quickstart approach, pipeline works as high-level helper.
    *     Automatically handles tokenization, model loading and output formatting.     
    *     Not ideal for model training and advanced workflows.
    *     Slightly overhead compared to manual loading.    

### Loading the Model Using Pipeline

In [ ]:
from transformers import pipeline

pipe = pipeline('text-generation', model='openai-community/gpt2') # task = text-generation

In [ ]:
prompt = "What is deep learning?"
output = pipe(prompt)

In [ ]:
print(output)
print(output[0]['generated_text'])

### Loading the Model using (AutoTokenizer + AutoModel)

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
import torch.nn.functional as F

tokenizer = AutoTokenizer.from_pretrained("openai-community/gpt2")
model = AutoModelForCausalLM.from_pretrained("openai-community/gpt2")

In [ ]:
print('Tokenizer: ', tokenizer)
print('Model Architecture: ', model)

### Tokenization

In [ ]:
sentence = 'unsure'
input_ids = tokenizer(sentence)['input_ids']
print(input_ids) # Return Token IDs
# input_ids = tokenizer(sentence, return_tensors='pt') # for PyTorch Tensor
# print(input_ids)
tokenizer.decode(input_ids[0]) # To get the text based on token id

sentence = 'unbelievable'
input_ids = tokenizer(sentence, return_tensors='pt').input_ids
print(input_ids) # Return Token IDs

In [32]:
for token_id in input_ids[0]:
  print(tokenizer.decode(token_id))

un
bel
iev
able


In [33]:
word = "homoscedasticity"
my_ids = tokenizer(word, return_tensors="pt").input_ids
my_ids

tensor([[26452,   418,   771,  3477,   414]])

In [34]:
tokenizer.decode(my_ids.squeeze())

'homoscedasticity'

In [35]:
word = "pneumonoultramicroscopicsilicovolcanoconiosis"
my_ids = tokenizer(word, return_tensors="pt").input_ids
# len(my_ids[0])
my_ids

tensor([[   79, 25668,   261, 25955,   859,  2500,  1416,   404,   873, 41896,
           709,   349,  5171, 36221, 42960]])

In [36]:
for token_id in my_ids.squeeze():
    print(tokenizer.decode(token_id))

p
neum
on
oult
ram
icro
sc
op
ics
ilic
ov
ol
can
ocon
iosis


In [37]:
sentence = "antidisestablishmentarianism"
token_ids = tokenizer(sentence, return_tensors="pt").input_ids
token_ids, len(token_ids[0])

(tensor([[  415, 29207, 44390,  3699,  1042]]), 5)

In [38]:
word = "floccinaucinihilipilification"

my_ids = tokenizer(word, return_tensors="pt").input_ids
my_ids, len(my_ids[0])

(tensor([[ 2704, 13966,   259, 14272,   259, 20898,   541,   346,  2649]]), 9)

In [39]:
for token_id in my_ids[0]:
    print(tokenizer.decode(token_id))

fl
occ
in
auc
in
ihil
ip
il
ification


### Text Generation

In [ ]:
gpt2 = AutoModelForCausalLM.from_pretrained("gpt2")
print('Model Architecture: ', gpt2)

### Predicting the Next Word

**Logits &mdash;** Logits are raw scores the model generates for each potential output in large language models (LLMs). While these logits are not probabilities, they offer valuable insight into how confident the model is about its predictions before they are transformed into final probabilities. A higher logit value indicates stronger confidence in a particular outcome, while lower values suggest more uncertainty.

*Below code block predicts the next word by GPT*.

In [58]:
sentence = "I learn machine learning to" #  It guessed when we execute this block several times and it goes on: --be able to do things that--
# We have to tokenize the string before passing to any GPT LLM i.e. Data Processing Technique
token_ids = tokenizer(sentence, return_tensors="pt").input_ids
# print(gpt2(token_ids).logits) # Its contain no. of vectors that the sentence have i.e. one word = one vector
outputs = gpt2(token_ids).logits[0, -1] # last word/token
tokenizer.decode(outputs.argmax()) # It guesses the next word

' be'

In [59]:
sentence = "I learn machine learning to enhance"
token_ids = tokenizer(sentence, return_tensors="pt").input_ids
outputs = gpt2(token_ids).logits[0, -1] # last word/token
final_logits = torch.topk(outputs, 20) # Feel free to play around with the K

for index in final_logits.indices:
    print(tokenizer.decode(index))

 our
 the
 my
 your
 human
 a
 and
 its
 their
 performance
 learning
 user
 data
 social
 real
 understanding
 information
,
 intelligence
 people
